#!/bin/bash
source test/config.sh
echo "Problem A tests"
echo "-----------------------------------------"
echo "Test: python accepted"
bin/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/accepted.py"
echo "-----------------------------------------"
echo "Test: python compilation error"
bin/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/compile.py"
echo "-----------------------------------------"
echo "Test: python tle too much output"
bin/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/tle1.py"
echo "-----------------------------------------"
echo "Test: python tle not enough output"
bin/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/tle2.py"
echo "-----------------------------------------"
echo "Test: python mle"
bin/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/mle.py"
echo "-----------------------------------------"
echo "Test: python runtime error before validation"
bin/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/runtime1.py"
echo "-----------------------------------------"
echo "Test: python runtime error after validation"
bin/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/runtime2.py"
echo "-----------------------------------------"
echo "Test: python wrong answer missing output"
bin/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/wrong1.py"
echo "-----------------------------------------"
echo "Test: python wrong answer too much output"
bin/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/wrong2.py"
echo "-----------------------------------------"
echo "Test: python wrong answer numbers dont match"
bin/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/wrong3.py"
echo "-----------------------------------------"
echo "Test: python wrong answer on testcase 2"
bin/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/wrong4.py"
echo "-----------------------------------------"
echo "Test: cpp accepted"
bin/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/accepted.cpp"
echo "-----------------------------------------"
echo "Test: cpp compile"
bin/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/compile.cpp"
echo "-----------------------------------------"
echo "Test: cpp runtime"
bin/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/runtime.cpp"
echo "-----------------------------------------"
echo "Test: cpp mle"
bin/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/mle.cpp"
echo "-----------------------------------------"
echo "Test: cpp tle"
bin/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/tle.cpp"
echo "-----------------------------------------"
echo "Test: cpp wrong"
bin/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/wrong.cpp"
