#!/bin/bash

ip="127.0.0.1"
port="27120"

echo "Problem A tests"
echo "-----------------------------------------"
echo "Test: python accepted"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/accepted.py"
echo "-----------------------------------------"
echo "Test: python compilation error"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/compile.py"
echo "-----------------------------------------"
echo "Test: python tle too much output"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/tle1.py"
echo "-----------------------------------------"
echo "Test: python tle not enough output"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/tle2.py"
echo "-----------------------------------------"
echo "Test: python mle"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/mle.py"
echo "-----------------------------------------"
echo "Test: python runtime error before validation"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/runtime1.py"
echo "-----------------------------------------"
echo "Test: python runtime error after validation"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/runtime2.py"
echo "-----------------------------------------"
echo "Test: python wrong answer missing output"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/wrong1.py"
echo "-----------------------------------------"
echo "Test: python wrong answer too much output"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/wrong2.py"
echo "-----------------------------------------"
echo "Test: python wrong answer numbers dont match"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/wrong3.py"
echo "-----------------------------------------"
echo "Test: python wrong answer on testcase 2"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "A" -f "test/problem1/test-py/wrong4.py"
echo "-----------------------------------------"
echo "Test: cpp accepted"
bin/dev/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/accepted.cpp"
echo "-----------------------------------------"
echo "Test: cpp compile"
bin/dev/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/compile.cpp"
echo "-----------------------------------------"
echo "Test: cpp runtime"
bin/dev/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/runtime.cpp"
echo "-----------------------------------------"
echo "Test: cpp mle"
bin/dev/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/mle.cpp"
echo "-----------------------------------------"
echo "Test: cpp tle"
bin/dev/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/tle.cpp"
echo "-----------------------------------------"
echo "Test: cpp wrong"
bin/dev/client -i "$ip" -t $port -u "team2" -p "team2" -l "cpp" -b "A" -f "test/problem1/test-cpp/wrong.cpp"
echo "========================================="
echo "Problem B tests"
echo "-----------------------------------------"
echo "Test: python accepted exact"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "B" -f "test/problem2/test-py/accepted1.py"
echo "-----------------------------------------"
echo "Test: python accepted a little off"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "B" -f "test/problem2/test-py/accepted2.py"
echo "-----------------------------------------"
echo "Test: python runtime bad type"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "B" -f "test/problem2/test-py/runtime.py"
echo "-----------------------------------------"
echo "Test: python wrong converted to int"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "B" -f "test/problem2/test-py/wrong1.py"
echo "-----------------------------------------"
echo "Test: python wrong too much off"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "B" -f "test/problem2/test-py/wrong2.py"
echo "-----------------------------------------"
echo "========================================="
echo "Problem C tests"
echo "-----------------------------------------"
echo "Test: python accepted"
bin/dev/client -i "$ip" -t $port -u "team1" -p "team1" -l "python3" -b "C" -f "test/problem3/test-py/accepted.py"
echo "-----------------------------------------"
