#!/bin/bash

ip="127.0.0.1"
port="27107"

echo "Test: python accepted"
bin/dev/client -i "$ip" -t "27107" -u "team1" -p "shape-untrue" -l "python3" -b "A" -f "example/problem1/test-py/accepted.py"
echo "=========================="
echo "Test: python compilation error"
bin/dev/client -i "$ip" -t "27107" -u "team1" -p "shape-untrue" -l "python3" -b "A" -f "example/problem1/test-py/compile.py"
echo "=========================="
echo "Test: python tle too much output"
bin/dev/client -i "$ip" -t "27107" -u "team1" -p "shape-untrue" -l "python3" -b "A" -f "example/problem1/test-py/tle1.py"
echo "=========================="
echo "Test: python tle not enough output"
bin/dev/client -i "$ip" -t "27107" -u "team1" -p "shape-untrue" -l "python3" -b "A" -f "example/problem1/test-py/tle2.py"
echo "=========================="
echo "Test: python mle"
bin/dev/client -i "$ip" -t "27107" -u "team1" -p "shape-untrue" -l "python3" -b "A" -f "example/problem1/test-py/mle.py"
echo "=========================="
echo "Test: python runtime error before validation"
bin/dev/client -i "$ip" -t "27107" -u "team1" -p "shape-untrue" -l "python3" -b "A" -f "example/problem1/test-py/runtime1.py"
echo "=========================="
echo "Test: python runtime error after validation"
bin/dev/client -i "$ip" -t "27107" -u "team1" -p "shape-untrue" -l "python3" -b "A" -f "example/problem1/test-py/runtime2.py"
echo "=========================="
echo "Test: python wrong answer missing output"
bin/dev/client -i "$ip" -t "27107" -u "team1" -p "shape-untrue" -l "python3" -b "A" -f "example/problem1/test-py/wrong1.py"
echo "=========================="
echo "Test: python wrong answer too much output"
bin/dev/client -i "$ip" -t "27107" -u "team1" -p "shape-untrue" -l "python3" -b "A" -f "example/problem1/test-py/wrong2.py"
echo "=========================="
echo "Test: python wrong answer numbers dont match"
bin/dev/client -i "$ip" -t "27107" -u "team1" -p "shape-untrue" -l "python3" -b "A" -f "example/problem1/test-py/wrong3.py"
echo "=========================="
echo "Test: python wrong answer on testcase 2"
bin/dev/client -i "$ip" -t "27107" -u "team1" -p "shape-untrue" -l "python3" -b "A" -f "example/problem1/test-py/wrong4.py"
echo "=========================="
echo "Test: cpp accepted"
bin/dev/client -i "$ip" -t "27107" -u "team2" -p "ugly-bacon" -l "cpp" -b "A" -f "example/problem1/test-cpp/accepted.cpp"
echo "=========================="
echo "Test: cpp compile"
bin/dev/client -i "$ip" -t "27107" -u "team2" -p "ugly-bacon" -l "cpp" -b "A" -f "example/problem1/test-cpp/compile.cpp"
echo "=========================="
echo "Test: cpp runtime"
bin/dev/client -i "$ip" -t "27107" -u "team2" -p "ugly-bacon" -l "cpp" -b "A" -f "example/problem1/test-cpp/runtime.cpp"
echo "=========================="
echo "Test: cpp mle"
bin/dev/client -i "$ip" -t "27107" -u "team2" -p "ugly-bacon" -l "cpp" -b "A" -f "example/problem1/test-cpp/mle.cpp"
echo "=========================="
echo "Test: cpp tle"
bin/dev/client -i "$ip" -t "27107" -u "team2" -p "ugly-bacon" -l "cpp" -b "A" -f "example/problem1/test-cpp/tle.cpp"
echo "=========================="
echo "Test: cpp wrong"
bin/dev/client -i "$ip" -t "27107" -u "team2" -p "ugly-bacon" -l "cpp" -b "A" -f "example/problem1/test-cpp/wrong.cpp"
echo "=========================="
